# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - .nojekyll
exclude:
ignore:
deploy:
  type: git
  repo: https://github.com/icelessusr/icelessusr.github.io.git
  branch: main
  ignore_hidden: false
